version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
      KC_IMPORT: /opt/keycloak/data/import/keycloak-realm.json
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json
    ports:
      - "8080:8080"
    command: start-dev --import-realm
